# Generated by Django 3.1.7 on 2021-08-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0004_car_is_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="seller_name_copy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
