# Generated by Django 3.1.7 on 2021-08-03 07:30
from django.db import migrations, models


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Car = apps.get_model("car", "Car")
    for car in Car.objects.all():
        car.seller_name_copy = car.seller_name
        car.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("car", "0005_car_seller_name_copy"),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
