# Generated by Django 3.1.7 on 2021-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0006_auto_20210803_0730"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="seller_name_copy2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
