# Generated by Django 3.1.7 on 2021-08-03 10:40

from django.db import migrations
from django.db.models import F


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Car = apps.get_model("car", "Car")
    Car.objects.update(seller_name_copy2=F("seller_name"))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("car", "0007_car_seller_name_copy2"),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
